### ISSUE TITLE
Error message:  code: -1021,enter code here msg: 'Timestamp for this request is outside of the recvWindow.'

### ISSUE THREAD

**Issue by vd3d** [copmorty/price_action_orders#9]
Hi,

When I try to login, I got the following message:

 code: -1021,enter code here msg: 'Timestamp for this request is outside of the recvWindow.'
 
 I have searched for the reason, and found a few articles, for example:
 https://stackoverflow.com/questions/69208437/binance-timestamp-error-timestamp-for-this-request-is-outside-of-the-recvwindow
 
 I have also fix the code on my side, now it works well. Please, let me know if you wish the fix ?

**Comment by copmorty** [comment]
Hello @vd3d, 

I've encountered this error before, it is related to out-of-sync system times and it can be resolved by synchronizing your system's time with the network time. As per the link you provided, it's also possible to increase tolerance for out-of-sync system times by setting the _recvWindow_ parameter to 60 seconds. I did a quick test, and it was successful. Nevertheless, I would be glad to see your code solution.

**Comment by vd3d** [comment]
For now it is also my solution, I changed the recvWindow.

If I understand the timestamp is important because if I have network delays, I can buy/sell at a different price than the one I expect. On a consumer PC I cannot sync the machine time with binance, but I suppose that there are other solutions.
